spring.application.name=movie-service

server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/movie-service
spring.datasource.username=postgres
spring.datasource.password=${DB_PWD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_APIKEY}
cloudinary.api-secret=${CLOUDINARY_SECRETKEY}

